### PR TITLE
fix(rifsc): remove unused parameter in stm32_rifsc_register_debugfs when DEBUG_FS is not set

### PR DESCRIPTION
**Pull request by JocelynMeyron-eaton**
This is the error I got when I compile the kernel without the CONFIG_DEBUG_FS option:
```
| ../../../../../../kernel-source/drivers/bus/stm32_rifsc.c:636:68: error: expected ';', ',' or ')' before '__unused'
|   636 | static int stm32_rifsc_register_debugfs(struct rifsc_private *priv __unused)
|       |                                                                    ^~~~~~~~
| ../../../../../../kernel-source/drivers/bus/stm32_rifsc.c: In function 'stm32_rifsc_probe':
| ../../../../../../kernel-source/drivers/bus/stm32_rifsc.c:910:14: error: implicit declaration of function 'stm32_rifsc_register_debugfs' [-Werror=implicit-function-declaration]
|   910 |         rc = stm32_rifsc_register_debugfs(rifsc_priv);
|       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| cc1: some warnings being treated as errors
```

Feel free to forward this fix to your internal team if you don't want to merge my PR.

### CODE REVIEW

**Comment by GseoC** [comment]
Hello Jocelyn,

Thank you for reporting this build error. Indeed, your patch is perfectly fine. Unfortunately, we cannot merge patches in this repository.
I will create a patch in our downstream for the next release. Would you like to share an e-mail address so I can add a `Reported-by:` tag or you don't care?

Thanks,
Gatien

**Comment by JocelynMeyron-eaton** [comment]
Hi Gatien, thanks for your quick answer. Here is my professional email address in case you want to use it: JocelynMeyron@eaton.com. Let me know once this new release is available.

**Comment by AdrianDC** [comment]
Patch confirmed working on kernel 6.6.78 over Yocto scarthgap current HEADs, thanks :+1: !

**Comment by JocelynMeyron-eaton** [comment]
Closing since it's now integrated in this commit https://github.com/STMicroelectronics/linux/commit/517e1a304744c5926bee3d03159336555ad1fee7, thanks @GseoC
